### ISSUE TITLE
Write Readme - tech requirements for contributors

### ISSUE THREAD

**Issue by brooksquil** [nash-rb/nashrb_website#3]
- ruby 5.2.1
 - rails 5
 - sqlite3
 - ERB for layouts and such
 - possibly Slim for forms and other partials?

Database Browser of choice such as DB browser

Consider Bin/Setup file

Rubocop -link to docs

**Comment by mellowfish** [comment]
Did we decide on ruby 2.5? John Sloan created the project with 2.4. We can maybe update that when this ticket is pulled in.

**Comment by brooksquil** [comment]
I don't recall if there was a consensus. Ans yes I think we can go ahead and update it, as you suggest when this ticket is pulled.
