### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by brooksquil** [nash-rb/nashrb_website#5]
Share in slack before scaffolding:

Tables:

Users
 - Roles string field
 - Can Can Gem?
Events
User-Events (tracks people who RSVP to event)
Blog
Companies
User-Company
Sponsorship 
Sponsor-company

**Comment by mellowfish** [comment]
Note: I am including an ERD generator in my authentication PR. It is updated after each `db:migrate`, but I think we should not check in the PDF since it is 30K with only two tables so far...

**Comment by mellowfish** [comment]
Unless people think it is worth keeping a large asset like that around.

**Comment by brooksquil** [comment]
That's fine with me. Excited to learn there is such a thing as an ERD generator.
